apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/app-root: /{{ .Values.appName }}/
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /translator-website(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: 80