# Generated by Django 5.1.4 on 2025-05-08 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLanguage',
            fields=[
                ('name', models.CharField(help_text='Язык программирования', max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Ip address')),
                ('req_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Time and date of request')),
                ('input_code', models.CharField(blank=True, help_text='Input code', max_length=5000)),
                ('output_code', models.CharField(blank=True, help_text='Output code', max_length=5000, null=True)),
                ('translating_status', models.CharField(blank=True, help_text='Translating information', max_length=150)),
                ('translating_errors', models.CharField(blank=True, help_text='Translating errors', max_length=300)),
                ('language', models.ForeignKey(blank=True, db_column='language_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supportlanguage', verbose_name='Выходной язык программирования')),
            ],
        ),
    ]
