# Generated by Django 5.1.4 on 2025-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Ip address')),
                ('req_date', models.DateTimeField(auto_now_add=True, help_text='Time and date of request')),
                ('pascal_code', models.CharField(blank=True, help_text='Pascal code', max_length=5000)),
                ('python_code', models.CharField(blank=True, help_text='Python code', max_length=5000, null=True)),
                ('translating_info', models.CharField(blank=True, help_text='Translating information', max_length=150)),
                ('translating_errors', models.CharField(blank=True, help_text='Translating errors', max_length=300)),
            ],
        ),
    ]
