# Generated by Django 5.1.4 on 2025-05-08 04:25

from django.db import migrations


def create_default_languages(apps, schema_editor):
    SupportLanguage = apps.get_model('main', 'SupportLanguage')
    languages = ['Python', 'Go']
    for lang in languages:
        SupportLanguage.objects.get_or_create(name=lang)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_languages),

    ]
