# Generated by Django 5.1.4 on 2025-01-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='translating_info',
            new_name='translating_status',
        ),
    ]
