# Generated by Django 5.1.4 on 2025-05-08 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_translating_info_history_translating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='req_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time and date of request'),
        ),
    ]
